package com.github.thunder413.datetimeutils;


public enum DateTimeStyle {
    S_MONTH_S_YEAR,
    F_MONTH_S_YEAR,
    F_MONTH_F_YEAR,
    S_MONTH_S_YEAR_TIME,
    F_MONTH_S_YEAR_TIME,
    F_MONTH_F_YEAR_TIME,
    S_MONTH_S_YEAR_AT_TIME,
    F_MONTH_S_YEAR_AT_TIME,
    F_MONTH_F_YEAR_AT_TIME,
    S_WEEK_S_MONTH_S_YEAR,
    S_WEEK_F_MONTH_S_YEAR,
    S_WEEK_F_MONTH_F_YEAR,
    F_WEEK_S_MONTH_S_YEAR,
    F_WEEK_F_MONTH_S_YEAR,
    F_WEEK_F_MONTH_F_YEAR,
    S_WEEK_S_MONTH_S_YEAR_TIME,
    S_WEEK_F_MONTH_S_YEAR_TIME,
    S_WEEK_F_MONTH_F_YEAR_TIME,
    F_WEEK_S_MONTH_S_YEAR_TIME,
    F_WEEK_F_MONTH_S_YEAR_TIME,
    F_WEEK_F_MONTH_F_YEAR_TIME,
    S_WEEK_S_MONTH_S_YEAR_AT_TIME,
    S_WEEK_F_MONTH_S_YEAR_AT_TIME,
    S_WEEK_F_MONTH_F_YEAR_AT_TIME,
    F_WEEK_S_MONTH_S_YEAR_AT_TIME,
    F_WEEK_F_MONTH_S_YEAR_AT_TIME,
    F_WEEK_F_MONTH_F_YEAR_AT_TIME,
    AGO_SHORT_STRING,
    AGO_FULL_STRING
}
